// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package book

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindBookRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindBookRequest) Reset()         { *m = FindBookRequest{} }
func (m *FindBookRequest) String() string { return proto.CompactTextString(m) }
func (*FindBookRequest) ProtoMessage()    {}
func (*FindBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *FindBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindBookRequest.Unmarshal(m, b)
}
func (m *FindBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindBookRequest.Marshal(b, m, deterministic)
}
func (m *FindBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindBookRequest.Merge(m, src)
}
func (m *FindBookRequest) XXX_Size() int {
	return xxx_messageInfo_FindBookRequest.Size(m)
}
func (m *FindBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindBookRequest proto.InternalMessageInfo

func (m *FindBookRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type FindBookResponse struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindBookResponse) Reset()         { *m = FindBookResponse{} }
func (m *FindBookResponse) String() string { return proto.CompactTextString(m) }
func (*FindBookResponse) ProtoMessage()    {}
func (*FindBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *FindBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindBookResponse.Unmarshal(m, b)
}
func (m *FindBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindBookResponse.Marshal(b, m, deterministic)
}
func (m *FindBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindBookResponse.Merge(m, src)
}
func (m *FindBookResponse) XXX_Size() int {
	return xxx_messageInfo_FindBookResponse.Size(m)
}
func (m *FindBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindBookResponse proto.InternalMessageInfo

func (m *FindBookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type Book struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*FindBookRequest)(nil), "book.FindBookRequest")
	proto.RegisterType((*FindBookResponse)(nil), "book.FindBookResponse")
	proto.RegisterType((*Book)(nil), "book.Book")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xcf, 0xcf,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xb4, 0xb9, 0xf8, 0xdd, 0x32,
	0xf3, 0x52, 0x9c, 0xf2, 0xf3, 0xb3, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24, 0xb8,
	0xd8, 0xb3, 0x53, 0x2b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60,
	0x5c, 0x25, 0x23, 0x2e, 0x01, 0x84, 0xe2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x39, 0x2e,
	0xb0, 0x41, 0x60, 0xa5, 0xdc, 0x46, 0x5c, 0x7a, 0x60, 0x1b, 0xc0, 0x2a, 0x20, 0x16, 0x38, 0x71,
	0xb1, 0x80, 0x78, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x10, 0x03, 0x59, 0x83, 0x98, 0x32, 0x53, 0x84,
	0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x98, 0xc0, 0x76, 0x40, 0x38, 0x20, 0xd1,
	0x82, 0xa2, 0xcc, 0xe4, 0x54, 0x09, 0x66, 0xb0, 0x42, 0x08, 0xc7, 0xc8, 0x83, 0x8b, 0x1b, 0x64,
	0x46, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x25, 0x17, 0x07, 0xcc, 0x19, 0x42, 0xa2,
	0x10, 0x0b, 0xd1, 0xfc, 0x20, 0x25, 0x86, 0x2e, 0x0c, 0x71, 0x6d, 0x12, 0x1b, 0xd8, 0xef, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xdd, 0xe2, 0x1c, 0x09, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	FindBook(ctx context.Context, in *FindBookRequest, opts ...grpc.CallOption) (*FindBookResponse, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) FindBook(ctx context.Context, in *FindBookRequest, opts ...grpc.CallOption) (*FindBookResponse, error) {
	out := new(FindBookResponse)
	err := c.cc.Invoke(ctx, "/book.BookService/FindBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	FindBook(context.Context, *FindBookRequest) (*FindBookResponse, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) FindBook(ctx context.Context, req *FindBookRequest) (*FindBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBook not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_FindBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).FindBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.BookService/FindBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).FindBook(ctx, req.(*FindBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "book.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindBook",
			Handler:    _BookService_FindBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
